#ifndef __SETTINGS_H__
#define __SETTINGS_H__

#define DELAY_UPDATE_SCREEN 400000
#define INCTEMENT_LEVEL_TIME 10000
#define MIN_DELAY_UPDATE_SCREEN 100000
#define WON_LEVEL 40

#define MAX_X 20
#define MAX_Y 20

#define MIN_DELTA_NEW_RAND_APPLE_X 3
#define MIN_DELTA_NEW_RAND_APPLE_Y 3
#define MAX_APPLE_WEIGHT 3

#endif /* __SETTINGS_H__ */
